---
services:
  web1:
    image: web
    build: ./web
    networks:
      - nginx
    mem_limit: 256m
    cpu_count: 1
    environment:
      SERVER: 1
  web2:
    image: web
    networks:
      - nginx
    mem_limit: 256m
    cpu_count: 1
    environment:
      SERVER: 2
  web3:
    image: web
    networks:
      - nginx
    mem_limit: 256m
    cpu_count: 1
    environment:
      SERVER: 3
  web4:
    image: web
    networks:
      - nginx
    mem_limit: 256m
    cpu_count: 1
    environment:
      SERVER: 4

  nginx:
    image: nginx
    volumes:
      - type: "bind"
        source: "nginx/nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
    build: ./nginx
    networks:
      - nginx
    ports:
      - "8080:80"
    depends_on:
      - web1
      - web2
      - web3
      - web4

networks:
  nginx:
    name: nginx
    driver: bridge
